In [68]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import math

In [ ]:
# I was able to load the data, and calculate the average, maximum, and minimum distances from each person.
# Created a three new series representing all of the new information.
# Will definitely be able to do more with the data given more time as I continue to study Python libraries.

In [70]:
# loading the data and displaying info
df = pd.read_table('CheckInData/checkin_dataset.csv', sep = ',')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25668 entries, 0 to 25667
Data columns (total 5 columns):
Unnamed: 0     25668 non-null int64
user           25668 non-null int64
timestamp      25668 non-null object
xcoordinate    25668 non-null float64
ycoordinate    25668 non-null float64
dtypes: float64(2), int64(2), object(1)
memory usage: 1002.7+ KB


0    1.0
1    3.0
2    5.0
3    NaN
4    6.0
5    8.0
dtype: float64

In [77]:
df['xcoordinate']

0        0.906835
1        0.928587
2        0.904091
3        0.906752
4        0.900641
5        0.899680
6        0.873765
7        0.913476
8        0.915256
9        0.916273
10       0.906847
11       0.905919
12       0.901493
13       0.904264
14       0.898657
15       0.885372
16       0.884462
17       0.926481
18       0.904266
19       0.904425
20       0.875620
21       0.900621
22       0.894725
23       0.911556
24       0.896705
25       0.895725
26       0.894769
27       0.885053
28       0.912030
29       0.905292
           ...   
25638    0.944468
25639    0.970065
25640    0.966601
25641    0.978843
25642    0.956143
25643    0.950733
25644    0.959514
25645    0.970499
25646    0.943649
25647    0.957838
25648    0.959622
25649    0.979135
25650    0.978101
25651    0.952058
25652    0.946096
25653    0.950750
25654    0.963100
25655    0.961126
25656    0.963377
25657    0.947093
25658    0.971392
25659    0.961979
25660    0.972953
25661    0.945709
25662    0

In [118]:
# count_x_vals = df['xcoordinate'].values
# diffs_x = count_x_vals[:-1] - count_x_vals[1:]
# diffs_x_squared = diffs_x ** 2
# diffs_x

array([-0.02175169,  0.02449596, -0.00266117, ...,  0.01496139,
       -0.00293887, -0.0038159 ])

In [79]:
# count_y_vals = df['ycoordinate'].values
# diffs_y = count_y_vals[:-1] - count_y_vals[1:]
# diffs_y_squared = diffs_y ** 2
# diffs_y_squared

array([  8.11103479e-04,   4.37667696e-04,   4.16913122e-04, ...,
         2.08719475e-05,   1.20511951e-04,   6.06485760e-06])

In [80]:
# distance_squared = diffs_x_squared + diffs_y_squared
# distance = np.sqrt(distance_squared)
# distance

array([ 0.03583628,  0.03221366,  0.02059114, ...,  0.01564337,
        0.01136437,  0.00454158])

In [106]:
# slicing the timestamp to get only the date attribute 
df['eventDate'] = df.timestamp.str.slice(0,10)
# organizing by the date
events = df.groupby('eventDate')
events.groups
# type(events)

{'2017-05-01': Int64Index([  490,   499,   508,   517,   526,   535,   544,   559,   567,
               575,
             ...
             24600, 24607, 24614, 24828, 24837, 24846, 24855, 24877, 24882,
             24887],
            dtype='int64', length=339),
 '2017-05-02': Int64Index([   31,    39,    47,    55,    63,    71,    79,   488,   497,
               506,
             ...
             25243, 25245, 25247, 25249, 25251, 25253, 25533, 25538, 25543,
             25548],
            dtype='int64', length=331),
 '2017-05-03': Int64Index([ 1341,  1348,  1355,  1445,  1451,  1457,  1463,  2279,  2287,
              2595,
             ...
             23216, 23219, 23222, 23426, 23435, 23444, 23796, 23804, 23812,
             23820],
            dtype='int64', length=252),
 '2017-05-04': Int64Index([  668,   670,   672,   774,   776,   778,   780,   782,   784,
              1806,
             ...
             24541, 24550, 24867, 24870, 24873, 25268, 25274, 25280, 25286,
     

In [167]:
#initializing three new Series
average_dist = pd.Series() 
max_dist = pd.Series()
min_dist = pd.Series()

In [184]:

for name, group in events:
    group_x_vals = group['xcoordinate'].values
    diffx = group_x_vals[:-1] - group_x_vals[1:] 
    # difference between each pair of x-values
    diffx_squared = diffx ** 2
    group_y_vals = group['ycoordinate'].values
    diffy = group_y_vals[:-1] = group_y_vals[1:]
    # difference of y values
    diffy_squared = diffy ** 2 
    squared_sum = diffx_squared + diffy_squared
    distance_points = np.sqrt(squared_sum)
    # distance formula

    avg_distance = distance_points.mean()
    max_distance = distance_points.max()
    min_distance = distance_points.min()
    average_dist = pd.Series(np.concatenate((average_dist.values, [avg_distance])))
    max_dist = pd.Series(np.concatenate((max_dist.values, [max_distance])))
    min_dist = pd.Series(np.concatenate((min_dist.values, [min_distance])))
    # adding each new value to respective Series
            
                    
    print(name, "average: ", avg_distance)
    print(name, "max: ", max_distance)
    print(name, "min: ", min_distance)
    # displaying values from each day


2017-05-01 average:  0.53802772092
2017-05-01 max:  1.81299926355
2017-05-01 min:  0.00996357451816
2017-05-02 average:  0.647107556864
2017-05-02 max:  1.83059331686
2017-05-02 min:  0.00971877168121
2017-05-03 average:  0.567139730598
2017-05-03 max:  1.49000275746
2017-05-03 min:  0.00820949050935
2017-05-04 average:  0.477230230326
2017-05-04 max:  1.82096431283
2017-05-04 min:  0.0265319284212
2017-05-05 average:  0.533803253471
2017-05-05 max:  1.80075356964
2017-05-05 min:  0.0102626712186
2017-05-06 average:  0.462591654537
2017-05-06 max:  1.84554857362
2017-05-06 min:  0.00617853363493
2017-05-07 average:  0.527215019658
2017-05-07 max:  1.82035464523
2017-05-07 min:  0.0204713422846
2017-05-08 average:  0.604633128674
2017-05-08 max:  1.8109589379
2017-05-08 min:  0.0225447885362
2017-05-09 average:  0.439565420674
2017-05-09 max:  1.81516137491
2017-05-09 min:  0.00218976986399
2017-05-10 average:  0.621132002903
2017-05-10 max:  1.72679838827
2017-05-10 min:  0.01526740116

In [188]:
# creating three new Series to add to dataframe
average_dist
max_dist
min_dist

0      0.009964
1      0.009719
2      0.008209
3      0.026532
4      0.010263
5      0.006179
6      0.020471
7      0.022545
8      0.002190
9      0.015267
10     0.010787
11     0.010575
12     0.001501
13     0.019969
14     0.012314
15     0.010553
16     0.021169
17     0.011590
18     0.015492
19     0.013990
20     0.013418
21     0.017388
22     0.010718
23     0.025849
24     0.004188
25     0.000906
26     0.022172
27     0.010403
28     0.006926
29     0.023453
         ...   
154    0.007632
155    0.009134
156    0.009198
157    0.007967
158    0.013364
159    0.017759
160    0.006812
161    0.004555
162    0.011323
163    0.000576
164    0.004908
165    0.015803
166    0.020922
167    0.033432
168    0.024429
169    0.010466
170    0.014457
171    0.030313
172    0.010551
173    0.011315
174    0.012887
175    0.010723
176    0.017685
177    0.012968
178    0.017822
179    0.017423
180    0.016296
181    0.023075
182    0.008532
183    0.021758
Length: 184, dtype: floa